/*
 ==============================================================================
 
 This file was auto-generated by the Introjucer!
 
 It contains the basic framework code for a JUCE plugin processor.
 
 ==============================================================================
 */

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
Chorus_auv3AudioProcessor::Chorus_auv3AudioProcessor()
:m_CurrentBufferSize(0)
{
    // use a default samplerate and vector size here, reset it later
    m_C74PluginState = (CommonState *)gen_exported::create(44100, 64);
    gen_exported::reset(m_C74PluginState);
    
    m_InputBuffers = new t_sample *[gen_exported::num_inputs()];
    m_OutputBuffers = new t_sample *[gen_exported::num_outputs()];
    
    for (int i = 0; i < gen_exported::num_inputs(); i++) {
        m_InputBuffers[i] = NULL;
    }
    for (int i = 0; i < gen_exported::num_outputs(); i++) {
        m_OutputBuffers[i] = NULL;
    }
    
}

Chorus_auv3AudioProcessor::~Chorus_auv3AudioProcessor()
{
    gen_exported::destroy(m_C74PluginState);
}

//==============================================================================
const String Chorus_auv3AudioProcessor::getName() const
{
    return JucePlugin_Name;
}

int Chorus_auv3AudioProcessor::getNumParameters()
{
    return gen_exported::num_params();
}

float Chorus_auv3AudioProcessor::getParameter (int index)
{
    t_param value;
    t_param min = gen_exported::getparametermin(m_C74PluginState, index);
    t_param range = fabs(gen_exported::getparametermax(m_C74PluginState, index) - min);
    
    gen_exported::getparameter(m_C74PluginState, index, &value);
    
    value = (value - min) / range;
    
    return value;
}

void Chorus_auv3AudioProcessor::setParameter (int index, float newValue)
{
    t_param min = gen_exported::getparametermin(m_C74PluginState, index);
    t_param range = fabs(gen_exported::getparametermax(m_C74PluginState, index) - min);
    t_param value = newValue * range + min;
    
    gen_exported::setparameter(m_C74PluginState, index, value, NULL);
}

const String Chorus_auv3AudioProcessor::getParameterName (int index)
{
    return String(gen_exported::getparametername(m_C74PluginState, index));
}

const String Chorus_auv3AudioProcessor::getParameterText (int index)
{
    String text = String(getParameter(index));
    text += String(" ");
    text += String(gen_exported::getparameterunits(m_C74PluginState, index));
    
    return text;
}

const String Chorus_auv3AudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String Chorus_auv3AudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool Chorus_auv3AudioProcessor::isInputChannelStereoPair (int index) const
{
    return gen_exported::num_inputs() == 2;
}

bool Chorus_auv3AudioProcessor::isOutputChannelStereoPair (int index) const
{
    return gen_exported::num_outputs() == 2;
}

bool Chorus_auv3AudioProcessor::acceptsMidi() const
{
#if JucePlugin_WantsMidiInput
    return true;
#else
    return false;
#endif
}

bool Chorus_auv3AudioProcessor::producesMidi() const
{
#if JucePlugin_ProducesMidiOutput
    return true;
#else
    return false;
#endif
}

bool Chorus_auv3AudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double Chorus_auv3AudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int Chorus_auv3AudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
    // so this should be at least 1, even if you're not really implementing programs.
}

int Chorus_auv3AudioProcessor::getCurrentProgram()
{
    return 0;
}

void Chorus_auv3AudioProcessor::setCurrentProgram (int index)
{
}

const String Chorus_auv3AudioProcessor::getProgramName (int index)
{
    return String();
}

void Chorus_auv3AudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void Chorus_auv3AudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
    
    // initialize samplerate and vectorsize with the correct values
    m_C74PluginState->sr = sampleRate;
    m_C74PluginState->vs = samplesPerBlock;
    
    assureBufferSize(samplesPerBlock);
}

void Chorus_auv3AudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void Chorus_auv3AudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    assureBufferSize(buffer.getNumSamples());
    
    // fill input buffers
    for (int i = 0; i < gen_exported::num_inputs(); i++) {
        if (i < getNumInputChannels()) {
            for (int j = 0; j < m_CurrentBufferSize; j++) {
                m_InputBuffers[i][j] = buffer.getReadPointer(i)[j];
            }
        } else {
            memset(m_InputBuffers[i], 0, m_CurrentBufferSize *  sizeof(double));
        }
    }
    
    // process audio
    gen_exported::perform(m_C74PluginState,
                           m_InputBuffers,
                           gen_exported::num_inputs(),
                           m_OutputBuffers,
                           gen_exported::num_outputs(),
                           buffer.getNumSamples());
    
    // fill output buffers
    for (int i = 0; i < getNumOutputChannels(); i++) {
        if (i < gen_exported::num_outputs()) {
            for (int j = 0; j < buffer.getNumSamples(); j++) {
                buffer.getWritePointer(i)[j] = m_OutputBuffers[i][j];
            }
        } else {
            buffer.clear (i, 0, buffer.getNumSamples());
        }
    }
}

//==============================================================================
bool Chorus_auv3AudioProcessor::hasEditor() const
{
    return false; // (change this to true if you choose to supply an editor)
}

AudioProcessorEditor* Chorus_auv3AudioProcessor::createEditor()
{
    return new Chorus_auv3AudioProcessorEditor (*this);
}

//==============================================================================
void Chorus_auv3AudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
    
    char *state;
    size_t statesize = gen_exported::getstatesize(m_C74PluginState);
    state = (char *)malloc(sizeof(char) * statesize);
    
    gen_exported::getstate(m_C74PluginState, state);
    destData.replaceWith(state, sizeof(char) * statesize);
    
    if (state) free(state);
}

void Chorus_auv3AudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
    gen_exported::setstate(m_C74PluginState, (const char *)data);
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new Chorus_auv3AudioProcessor();
}

//==============================================================================
// C74 added methods

void Chorus_auv3AudioProcessor::assureBufferSize(long bufferSize)
{
    if (bufferSize > m_CurrentBufferSize) {
        for (int i = 0; i < gen_exported::num_inputs(); i++) {
            if (m_InputBuffers[i]) delete m_InputBuffers[i];
            m_InputBuffers[i] = new t_sample[bufferSize];
        }
        for (int i = 0; i < gen_exported::num_outputs(); i++) {
            if (m_OutputBuffers[i]) delete m_OutputBuffers[i];
            m_OutputBuffers[i] = new t_sample[bufferSize];
        }
        
        m_CurrentBufferSize = bufferSize;
    }
}
